server:
  port: 8001

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_account?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: password
  jpa:
    show-sql: true
